openapi: 3.0.0
info:
  title: E-commerce BFF API
  version: 1.0.0
  description: API for frontend to interact with backend services

paths:
  /users/register:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created successfully

  /users/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /users/logout:
    post:
      summary: Logout a user
      responses:
        '200':
          description: User logged out

  /items:
    get:
      summary: Get list of items
      responses:
        '200':
          description: List of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemAllResponse'

  /items/{itemType}:
    get:
      summary: Get item details
      parameters:
        - in: path
          name: itemType
          schema:
            type: string
          required: true
          description: Item type
      responses:
        '200':
          description: Item details retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ItemTypeResponse'

  /items/{itemType}/{itemId}:
    get:
      summary: Get item details
      parameters:
        - in: path
          name: itemType
          schema:
            type: string
          required: true
          description: Item ID
        - in: path
          name: itemId
          schema:
            type: integer
          required: true
          description: Item ID
      responses:
        '200':
          description: Item details retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemDetailResponse'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        password:
          type: string
        zipcode:
          type: string
        prefecture:
          type: string
        municipalities:
          type: string
        address:
          type: string
        telephone:
          type: string

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        token:
          type: string

    Item:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        price:
          type: integer
        imagePath:
          type: string

    Top:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        price:
          type: integer
        imagePath:
          type: string
        deleted:
          type: boolean

    Bottom:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        price:
          type: integer
        imagePath:
          type: string
        deleted:
          type: boolean

    Set:
      type: object
      properties:
        id:
          type: integer
        topId:
          type: integer
        bottomId:
          type: integer
        name:
          type: string
        description:
          type: string
        price:
          type: integer
        imagePath:
          type: string
    
    ItemAllResponse:
      type: object
      properties:
        set:
          type: array
          items: 
            $ref: '#/components/schemas/Set'
        top:
          type: array
          items: 
            $ref: '#/components/schemas/Top'
        buttom:
          type: array
          items:
            $ref: '#/components/schemas/Bottom'

    ItemTypeResponse:
      type: object
      properties:
        items:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/Set'
              - $ref: '#/components/schemas/Top'
              - $ref: '#/components/schemas/Bottom'

    
    ItemDetailResponse:
      type: object
      properties:
        item:
          oneOf:
            - $ref: '#/components/schemas/Set'
            - $ref: '#/components/schemas/Top'
            - $ref: '#/components/schemas/Bottom'
      
    Inventory:
      type: object
      properties:
        id:
          type: integer
        itemId:
          type: integer
        itemType:
          type: string
        stockQuantity:
          type: integer

    Order:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        status:
          type: string
          enum: [BEFORE_ORDER, UNPAID, PAID, SHIPPED, DELIVERED, CANCELED]
        totalPrice:
          type: integer
        orderDate:
          type: string
          format: date-time
        paymentMethodId:
          type: integer
        deliveryDate:
          type: string
          format: date
        addressId:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'

    OrderItem:
      type: object
      properties:
        id:
          type: integer
        orderId:
          type: integer
        itemId:
          type: integer
        itemType:
          type: string
          enum: [TOP, BOTTOM, SET]
        quantity:
          type: integer
        size:
          type: string

    OrderStatusUpdate:
      type: object
      properties:
        status:
          type: string
          enum: [BEFORE_ORDER, UNPAID, PAID, SHIPPED, DELIVERED, CANCELED]

    PaymentMethod:
      type: object
      properties:
        id:
          type: integer
        methodName:
          type: string

    ComparisonScenario:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        imagePath:
          type: string
        timeOfDay:
          type: string
          enum: [DAY, NIGHT]
        weather:
          type: string
          enum: [SUNNY, RAINY]
        location:
          type: string
          enum: [OFFICE, OUTDOOR]

    FavoriteSet:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        setId:
          type: integer
        createdAt:
          type: string
          format: date-time

    FavoriteSetComparison:
      type: object
      properties:
        id:
          type: integer
        favoriteSetId:
          type: integer
        comparisonScenarioId:
          type: integer
        comparisonResult:
          type: string
